### ISSUE TITLE
Getting unknown property

### ISSUE THREAD

**Issue by sarxan26** [yii2tech/ar-variation#15]
I have a kinda weird problem.
Multiple insertion is working, but when I retrieve data (for example title) from EventTranslation table, I'm getting UnknownPropertyException
Here is my models:

```
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "Language".
 *
 * @property string $locale
 * @property string $name
 */
class Language extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Language';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['locale'], 'required'],
            [['locale'], 'string', 'max' => 5],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'locale' => 'Locale',
            'name' => 'Name',
        ];
    }
}
```

```
<?php

namespace common\models;

use Yii;
use yii2tech\ar\variation\VariationBehavior;
/**
 * This is the model class for table "Event".
 *
 * @property integer $id
 * @property integer $gallery_id
 * @property string $date
 * @property string $created_at
 * @property string $youtube_url
 * @property string $img_url
 *
 * @property Gallery $gallery
 * @property EventTranslation[] $eventTranslations
 * @property Language[] $languages
 */
class Event extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */


    public static function tableName()
    {
        return 'Event';
    }

    public function behaviors()
    {
        return [
            'translations' => [
                'class' => VariationBehavior::className(),
                'variationsRelation' => 'translations',
                'defaultVariationRelation' => 'defaultTranslation',
                'variationOptionReferenceAttribute' => 'language',
                'optionModelClass' => Language::className(),
                'defaultVariationOptionReference' => Yii::$app->language,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['gallery_id'], 'integer'],
            [['created_at'], 'safe'],
            [['date', 'youtube_url', 'img_url'], 'string', 'max' => 255],
            [['gallery_id'], 'exist', 'skipOnError' => true, 'targetClass' => Gallery::className(), 'targetAttribute' => ['gallery_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'gallery_id' => 'Gallery ID',
            'date' => 'Date',
            'created_at' => 'Created At',
            'youtube_url' => 'Youtube Url',
            'img_url' => 'Img Url',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGallery()
    {
        return $this->hasOne(Gallery::className(), ['id' => 'gallery_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTranslations()
    {
        return $this->hasMany(EventTranslation::className(), ['event_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDefaultTranslation()
    {
        return $this->hasDefaultVariationRelation();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLanguages()
    {
        return $this->hasMany(Language::className(), ['locale' => 'language'])->viaTable('EventTranslation', ['event_id' => 'id']);
    }


}
```

```
<?php

namespace common\models;

use Yii;
use common\behaviors\SluggableBehavior;

/**
 * This is the model class for table "EventTranslation".
 *
 * @property integer $event_id
 * @property string $language
 * @property string $title
 * @property string $preview
 * @property string $description
 * @property string $slug
 *
 * @property Event $event
 * @property Language $language0
 */
class EventTranslation extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'EventTranslation';
    }

    public function behaviors()
    {
        return [
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'title',
                'ensureUnique' => true
            ],
        ];
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['event_id'], 'integer'],
            [['preview', 'description'], 'string'],
            [['language'], 'string', 'max' => 5],
            [['title', 'slug'], 'string', 'max' => 255],
            [['event_id'], 'exist', 'skipOnError' => true, 'targetClass' => Event::className(), 'targetAttribute' => ['event_id' => 'id']],
            [['language'], 'exist', 'skipOnError' => true, 'targetClass' => Language::className(), 'targetAttribute' => ['language' => 'locale']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'event_id' => 'Event ID',
            'language' => 'Language',
            'title' => 'Title',
            'preview' => 'Preview',
            'description' => 'Description',
            'slug' => 'Slug',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(Event::className(), ['id' => 'event_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLanguage0()
    {
        return $this->hasOne(Language::className(), ['locale' => 'language']);
    }
}

```

**Comment by klimov-paul** [comment]
What is a full exception stack trace?

**Comment by sarxan26** [comment]
```
Stack trace:
#0 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/db/BaseActiveRecord.php(286): yii\base\Component->__get('title')
#1 /usr/share/nginx/yusuf/backend/views/site/index.php(6): yii\db\BaseActiveRecord->__get('title')
#2 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/base/View.php(326): require('/usr/share/ngin...')
#3 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/base/View.php(248): yii\base\View->renderPhpFile('/usr/share/ngin...', Array)
#4 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/base/View.php(150): yii\base\View->renderFile('/usr/share/ngin...', Array, Object(backend\controllers\SiteController))
#5 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/base/Controller.php(378): yii\base\View->render('index', Array, Object(backend\controllers\SiteController))
#6 /usr/share/nginx/yusuf/backend/controllers/SiteController.php(75): yii\base\Controller->render('index', Array)
#7 [internal function]: backend\controllers\SiteController->actionIndex()
#8 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#9 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#10 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('', Array)
#11 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/web/Application.php(100): yii\base\Module->runAction('', Array)
#12 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#13 /usr/share/nginx/yusuf/backend/web/index.php(18): yii\base\Application->run()
#14 {main}
```

**Comment by klimov-paul** [comment]
So you are missing `title` field. From where exactly are you trying to get it?

**Comment by sarxan26** [comment]
In backend event's index page.

```
<?php

use yii\helpers\Html;
use yii\grid\GridView;


/* @var $this yii\web\View */
/* @var $searchModel backend\models\EventSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Events';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="event-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Event', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],



            'title',

            'gallery_id',


            'date',
            'created_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>
```

exception stack trace:

```
Stack trace:
#0 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/db/BaseActiveRecord.php(286): yii\base\Component->__get('title')
#1 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php(210): yii\db\BaseActiveRecord->__get('title')
#2 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/grid/DataColumn.php(214): yii\helpers\BaseArrayHelper::getValue(Object(common\models\Event), 'title')
#3 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/grid/DataColumn.php(225): yii\grid\DataColumn->getDataCellValue(Object(common\models\Event), 5, 0)
#4 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/grid/Column.php(108): yii\grid\DataColumn->renderDataCellContent(Object(common\models\Event), 5, 0)
#5 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/grid/GridView.php(504): yii\grid\Column->renderDataCell(Object(common\models\Event), 5, 0)
#6 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/grid/GridView.php(473): yii\grid\GridView->renderTableRow(Object(common\models\Event), 5, 0)
#7 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/grid/GridView.php(344): yii\grid\GridView->renderTableBody()
#8 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/widgets/BaseListView.php(151): yii\grid\GridView->renderItems()
#9 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/grid/GridView.php(313): yii\widgets\BaseListView->renderSection('{items}')
#10 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/widgets/BaseListView.php(126): yii\grid\GridView->renderSection('{items}')
#11 [internal function]: yii\widgets\BaseListView->yii\widgets\{closure}(Array)
#12 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/widgets/BaseListView.php(129): preg_replace_callback('/{\w+}/', Object(Closure), '{summary}?{item...')
#13 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/grid/GridView.php(288): yii\widgets\BaseListView->run()
#14 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/base/Widget.php(102): yii\grid\GridView->run()
#15 /usr/share/nginx/yusuf/backend/views/event/index.php(50): yii\base\Widget::widget(Array)
#16 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/base/View.php(326): require('/usr/share/ngin...')
#17 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/base/View.php(248): yii\base\View->renderPhpFile('/usr/share/ngin...', Array)
#18 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/base/View.php(150): yii\base\View->renderFile('/usr/share/ngin...', Array, Object(backend\controllers\EventController))
#19 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/base/Controller.php(378): yii\base\View->render('index', Array, Object(backend\controllers\EventController))
#20 /usr/share/nginx/yusuf/backend/controllers/EventController.php(77): yii\base\Controller->render('index', Array)
#21 [internal function]: backend\controllers\EventController->actionIndex()
#22 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#23 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#24 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('index', Array)
#25 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/web/Application.php(100): yii\base\Module->runAction('event/index', Array)
#26 /usr/share/nginx/yusuf/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#27 /usr/share/nginx/yusuf/backend/web/index.php(18): yii\base\Application->run()
#28 {main}

```

**Comment by klimov-paul** [comment]
How do you create your data provider?

**Comment by sarxan26** [comment]
```
public function actionIndex()
    {
        $searchModel = new EventSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
```

```
class EventSearch extends Event
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'gallery_id'], 'integer'],
            [['date', 'created_at', 'youtube_url', 'img_url'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = Event::find();

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'id' => $this->id,
            'gallery_id' => $this->gallery_id,
            'created_at' => $this->created_at,
        ]);

        $query->andFilterWhere(['like', 'date', $this->date])
            ->andFilterWhere(['like', 'youtube_url', $this->youtube_url])
            ->andFilterWhere(['like', 'img_url', $this->img_url]);

        return $dataProvider;
    }
}

```

**Comment by klimov-paul** [comment]
Unable to reproduce.

Most probably you do not have a corresponding record for `defaultVariationRelation` for at least one record in your `Event` list.
You should either ensure default variation exists for each record or setup `variationAttributeDefaultValueMap`.
